-- ============================================================
-- StockInfo - Complete Database Creation Script
-- Run this once in MySQL Workbench / CLI before starting the app
-- ============================================================

DROP DATABASE IF EXISTS stockinfo_db;
CREATE DATABASE stockinfo_db;
USE stockinfo_db;

-- 1. ROLES
CREATE TABLE roles (
    role_id     INT AUTO_INCREMENT PRIMARY KEY,
    role_name   VARCHAR(20) NOT NULL UNIQUE
);

-- 2. USERS
CREATE TABLE users (
    user_id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    full_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL UNIQUE,
    password      VARCHAR(255) NOT NULL,
    phone_number  VARCHAR(15),
    role_id       INT NOT NULL,
    is_active     BOOLEAN DEFAULT TRUE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

-- 3. STOCKS
CREATE TABLE stocks (
    stock_id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    symbol         VARCHAR(20) NOT NULL UNIQUE,
    company_name   VARCHAR(150) NOT NULL,
    sector         VARCHAR(100),
    exchange       VARCHAR(20),
    current_price  DECIMAL(12,2) NOT NULL,
    day_change_pct DECIMAL(6,2) DEFAULT 0.00,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 4. PRICE_HISTORY
CREATE TABLE price_history (
    history_id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    stock_id     BIGINT NOT NULL,
    price_date   DATE NOT NULL,
    open_price   DECIMAL(12,2),
    close_price  DECIMAL(12,2),
    high_price   DECIMAL(12,2),
    low_price    DECIMAL(12,2),
    volume       BIGINT,
    FOREIGN KEY (stock_id) REFERENCES stocks(stock_id) ON DELETE CASCADE,
    UNIQUE KEY uq_stock_date (stock_id, price_date)
);

-- 5. PORTFOLIOS
CREATE TABLE portfolios (
    portfolio_id  BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id       BIGINT NOT NULL UNIQUE,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- 6. TRANSACTIONS
CREATE TABLE transactions (
    transaction_id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    portfolio_id     BIGINT NOT NULL,
    stock_id         BIGINT NOT NULL,
    transaction_type ENUM('BUY','SELL') NOT NULL,
    quantity         INT NOT NULL,
    price_per_unit   DECIMAL(12,2) NOT NULL,
    transaction_date DATE NOT NULL,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (portfolio_id) REFERENCES portfolios(portfolio_id) ON DELETE CASCADE,
    FOREIGN KEY (stock_id) REFERENCES stocks(stock_id)
);

-- 7. WATCHLIST
CREATE TABLE watchlist (
    watchlist_id  BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    stock_id      BIGINT NOT NULL,
    added_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (stock_id) REFERENCES stocks(stock_id) ON DELETE CASCADE,
    UNIQUE KEY uq_user_stock (user_id, stock_id)
);

-- 8. ACTIVITY_LOGS
CREATE TABLE activity_logs (
    log_id        BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id       BIGINT NOT NULL,
    action        VARCHAR(100) NOT NULL,
    description   VARCHAR(255),
    ip_address    VARCHAR(45),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ============================================================
-- Seed reference data (roles must exist before any user can register)
-- ============================================================
INSERT INTO roles (role_name) VALUES ('ROLE_ADMIN'), ('ROLE_USER');

-- Optional: a starter admin account.
-- Replace the password hash with a real BCrypt hash generated by
-- the application (e.g. via a one-time registration + manual role update).
-- INSERT INTO users (full_name, email, password, phone_number, role_id, is_active)
-- VALUES ('Admin User', 'admin@stockinfo.com', '$2a$10$REPLACE_WITH_REAL_BCRYPT_HASH', '9999999999', 1, TRUE);

-- Optional: sample stock master data for development/testing
INSERT INTO stocks (symbol, company_name, sector, exchange, current_price, day_change_pct) VALUES
('TCS', 'Tata Consultancy Services', 'IT', 'NSE', 3850.50, 1.25),
('INFY', 'Infosys Ltd', 'IT', 'NSE', 1540.75, -0.80),
('RELIANCE', 'Reliance Industries', 'Energy', 'NSE', 2980.00, 0.45),
('HDFCBANK', 'HDFC Bank Ltd', 'Banking', 'NSE', 1650.20, 0.10),
('TATAMOTORS', 'Tata Motors Ltd', 'Automobile', 'NSE', 985.60, -1.50);
